import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const out = 'demo-capture';
await mkdir(out, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1920, height: 1080 }, recordVideo: { dir: out, size: { width: 1920, height: 1080 } }, locale: 'en-US', timezoneId: 'UTC' });
// No microphone, camera, credentials, network mocking, or product DOM changes.
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push({type:'pageerror', message:error.message}));
page.on('requestfailed', request => errors.push({type:'requestfailed', url:request.url(), failure:request.failure()}));
const started = performance.now();
const marks = [];
const mark = async (name, seconds = 0) => {
  marks.push({ name, seconds: (performance.now() - started) / 1000 });
  await page.screenshot({ path: `${out}/${name}.png` });
  if (seconds) await page.waitForTimeout(seconds * 1000);
};
const body = () => page.locator('#app').innerText();
const scrollTo = async selector => { await page.locator(selector).scrollIntoViewIfNeeded(); await page.waitForTimeout(700); };
try {
  await page.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: 'Pick your sparring partner', exact: true }).waitFor();
  await mark('01-home', 6);
  await page.getByRole('button', { name: /The Frozen Account/ }).click();
  await mark('02-incoming', 5);
  await page.getByRole('button', { name: 'Answer call (A)', exact: true }).click();
  await mark('03-caller', 9);
  await page.getByRole('button', { name: 'Yes, what do you need?', exact: true }).click();
  await mark('04-code-request', 14);
  await page.getByRole('button', { name: 'Okay, the code is 4 8 1 5 1 6', exact: true }).click();
  await page.getByRole('heading', { name: 'Call Autopsy', exact: true }).waitFor();
  assert.match(await body(), /Scammed/);
  assert.match(await body(), /• • • • • •/);
  await mark('05-scammed-autopsy', 14);
  await scrollTo('.hang-callout');
  await mark('06-hangup-moment', 12);
  await scrollTo('.tl.hang-point');
  await mark('07-trigger-transcript', 12);
  await scrollTo('.script');
  await mark('08-safer-script', 10);
  await page.getByRole('button', { name: 'Retry this call', exact: true }).click();
  await mark('09-retry-incoming', 4);
  await page.getByRole('button', { name: 'Answer call (A)', exact: true }).click();
  await mark('10-retry-caller', 4);
  await page.getByRole('textbox', { name: 'Your reply', exact: true }).pressSequentially("I don't share codes.", { delay: 70 });
  await mark('11-refusal-typed', 3);
  await page.getByRole('button', { name: 'Send reply', exact: true }).click();
  assert.match(await body(), /next 10 minutes/);
  await mark('12-countdown-pressure', 9);
  await page.getByRole('button', { name: 'I’ll call the number on the back of my card.', exact: true }).click();
  await page.getByRole('heading', { name: 'Call Autopsy', exact: true }).waitFor();
  assert.match(await body(), /Survived/);
  assert.match(await body(), /Verified independently/);
  await mark('13-safe-outcome', 9);
  await page.locator('.tl.user').last().scrollIntoViewIfNeeded(); await page.waitForTimeout(700);
  await mark('14-independent-verification', 8);
  await scrollTo('.script');
  await mark('15-safety-script', 5);
  await page.getByRole('button', { name: 'Back to the dojo', exact: true }).click();
  await mark('16-six-scenarios', 7);
  await page.getByRole('button', { name: 'Voice & settings', exact: true }).click();
  assert.equal(await page.locator('#coach').isChecked(), true);
  await mark('17-text-coach-settings', 5);
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await mark('18-close-home', 7);
  assert.deepEqual(errors, [], 'Unexpected browser errors');
  await writeFile(`${out}/ui-verification.txt`, 'Verified genuine bank-code Scammed outcome, masked code, hang-up trigger, retry, refusal, countdown pressure, independently found card-number verification, Survived outcome, six scenarios and default text-only coach mode. No product state was injected.\n');
} finally {
  await writeFile(`${out}/browser-errors.json`, JSON.stringify(errors, null, 2));
  await writeFile(`${out}/marks.json`, JSON.stringify({ sourceCommit: process.env.GITHUB_SHA || null, viewport: {width:1920,height:1080}, marks }, null, 2));
  const video = page.video();
  await context.close();
  if (video) await video.saveAs(`${out}/dojo-current-build.webm`);
  await browser.close();
}
